image: "python:3.7"

tags:
  - azure-ci-cd
  
before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - build
  - test

pylint:
  stage: build
  script:
  - pylint -d C0301 src/main.py

pytest:
  stage: test
  script:
  - cd test/
  - pytest -v